---
title: "EH Analysis"
author: "Long Vuong"
date: "06/01/2021"
output: html_document
---

---
title: "Zero Punctuation Youtube Playlist Analysis"
author: "Long Vuong"
date: "28/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


maybe use size (increase size of geom_point() dots for views?)


```{r basic stuff, echo=T, results='hide'}
path <- paste(Sys.getenv("USERPROFILE"),"/Documents/GitHub/EH-Youtube", sep = "")
setwd(path)

#https://stackoverflow.com/a/8538071 --- date in a
series_csv <- c('./EH Series Sorted ', format(Sys.time(), "%Y-%m-%d"), '.csv')
series_csv <- paste(series_csv, collapse ="")

#https://stackoverflow.com/questions/22974765/  >>> fileEncoding="UTF-8-BOM"
#get rid of weird symbol in dates
#header = FALSE, or else names(yt/wikia) will replace first row
eh<- read.csv(file = series_csv, fileEncoding="UTF-8-BOM", header = FALSE)


names(eh) <- c('title', 'series', 'date', 'views', 'likes', 
               'dislikes', 'comments', 'id', 'duration')

#https://stackoverflow.com/q/29150252/6030118   sapply + gsub together
#https://stackoverflow.com/q/7992436/6030118    remove Extra History
eh[,1] <- sapply(eh[,1], function(x) gsub("\\- Extra History ","",as.character(x)))

#struggled before because put these before names(yt/wikia), so R doesn't
#know what yt/wikia$date is
eh$date <- as.Date(eh$date, '%Y-%m-%d')
eh$series <- as.factor(eh$series)
#str((eh))

eh[, 'year'] <- as.numeric(format(as.Date(eh$date, format='%Y-%m-%d'),"%Y"))
eh$year <- factor(eh$year, ordered = TRUE, levels =c(2013:2021))



library("plyr")
library("tidyverse")
library("scales")
library("plotly")
```


```{r derivative columns, echo=T, results='hide'}
#not all the times use pipe %>% 
#https://stackoverflow.com/questions/22867077/  >>> need to assign output to something
eh <- mutate(eh, daysSince = as.Date(Sys.Date()) - date)  #convert everything to date obj 
eh$daysSince <- as.numeric(eh$daysSince)                  #convert dateSince from date to numeiric
eh <- mutate(eh, viewsPerDay = round(views/daysSince))    #round viewsPerDay to nearest integer

#yt <- yt[ ,c(1,9,10,3:6,8,2,7)]       #rearrange columns; datesSince/viewsPerDay 2nd/3rd, dates/id 9/10th

#https://stackoverflow.com/a/49343023/6030118
eh <- eh %>%
  group_by(series) %>% 
  mutate(epNo = row_number())

#https://stackoverflow.com/a/26114852/6030118
#similar idea but can't use summarise, have to use transmute
eh1 <- eh %>% 
  group_by(series) %>% 
  transmute(seriesLength = length(series))

eh <- cbind(eh, eh1[,2])
rm(eh1)


#https://swcarpentry.github.io/r-novice-gapminder/12-plyr/
#based on series, select the final episode
last_eps <- ddply(
  .data = eh,
  .variables = "series",
  .fun = function(x) tail(x,n=1)
)

#based on the finished date, assign series number
last_eps <- last_eps %>% 
  arrange(date) %>% 
  transmute(series, seriesNo = c(1:nlevels(eh$series)))

eh <- eh %>% 
  inner_join(last_eps, by = c('series' = 'series'))


sum_views <- eh %>%
  arrange(seriesNo) %>% 
  transmute(series, seriesNo, views, year) %>% 
  group_by(seriesNo, series) %>% 
  summarise(seriesViews = sum(views), .groups ="keep")

```

```{r factors}
#eh$year <- factor(eh$year, ordered = TRUE, levels =c(2013:2021))
eh$epNo <- factor(eh$epNo, ordered = TRUE)
eh$seriesLength <- factor(eh$seriesLength, ordered = TRUE)
eh$seriesNo <- factor(eh$seriesNo, ordered = TRUE)
```


```{r year summary, fig.width=17, fig.height=12, eval= FALSE}
#https://www.r-graph-gallery.com/267-reorder-a-variable-in-ggplot2.html >>> fct_reorder
ap <- ggplot(sum_views, aes(x = seriesViews, y = fct_reorder(series,seriesNo, .desc = TRUE))) + 
  geom_point(size=3) + 
  theme(axis.text.y = element_text(angle = 0, vjust = 0.25)) + 
  labs(title = "Breaking Down Extra History Viewership By Series\n", x = "Views", y = "Series") 

ap <- ap + scale_x_continuous( labels = comma) + 
  geom_hline(yintercept=1.5) +  
  geom_hline(yintercept=11.5) + 
  geom_hline(yintercept=24.5) +     
  geom_hline(yintercept=36.5) + 
  geom_hline(yintercept=47.5) + 
  geom_hline(yintercept=58.5) + 
  geom_hline(yintercept=64.5) + 
  geom_hline(yintercept=66.5) +  
  annotate("text", label = "2021", x = 5900000, y = 1) + 
  annotate("text", label = "2020", x = 5900000, y = 11)+  
  annotate("text", label = "2019", x = 5900000, y = 24)+  
  annotate("text", label = "2018", x = 5900000, y = 36)+  
  annotate("text", label = "2017", x = 5900000, y = 47)+  
  annotate("text", label = "2016", x = 5900000, y = 58)+ 
  annotate("text", label = "2015", x = 5900000, y = 64)+  
  annotate("text", label = "2014", x = 5900000, y = 66)+  
  annotate("text", label = "2013", x = 5900000, y = 67.25)

ap
```


https://stackoverflow.com/questions/15624656/label-points-in-geom-point
https://stackoverflow.com/questions/47667994/ggplot-x-axis-labels-with-all-x-axis-values/47668790#47668790
```{r good stuff, fig.width=17, fig.height=11}

#order the series (factor) by year (factor) -> need to convert year to numeric
#https://forcats.tidyverse.org/reference/fct_reorder.html#arguments
#adapted idea for alternating  year color from here
#https://stackoverflow.com/a/49277491
#https://stackoverflow.com/a/23637666 
#have to pass as.numeric( seriesNo), cant fct_reorder an already factor
#put size = (epNo == 1) in ggplot if want first episode dot to be bigger
dp <- ggplot(eh, aes(x = views, y = fct_reorder(series,as.numeric(seriesNo), .desc = TRUE),
  color = (as.numeric(year) %% 2 == 0))) +
  geom_point(shape = 1, size = 2) + 
  theme(axis.text.y = element_text(angle = 0, vjust = 0.25)) + 
  
  labs(
    title = "Extra History's Series Viewership, Organized by Series' Upload Order\n", 
    x = "Views", 
    y = "Series' Name", 
    color = "Year\n", 
    size = "First Episode") +
  
  scale_color_manual(labels = c("Odd Year", "Even Year"), values = c("orange", "green")) 



# scale_x_continuous(minor_breaks = seq(1, 10, 1))

#https://stackoverflow.com/a/14564102
require(scales)

#https://ggplot2.tidyverse.org/reference/annotate.html
# dp <- dp + scale_x_continuous(labels = comma) + 
#   geom_hline(yintercept=1.5) +  
#   geom_hline(yintercept=11.5) + 
#   geom_hline(yintercept=23.5) +     
#   geom_hline(yintercept=36.5) + 
#   geom_hline(yintercept=47.5) + 
#   geom_hline(yintercept=58.5) + 
#   geom_hline(yintercept=64.5) + 
#   geom_hline(yintercept=66.5) +  
#   annotate("text", label = "2021", x = 5900000, y = 1) +  
#   annotate("text", label = "2020", x = 5900000, y = 11)+  
#   annotate("text", label = "2019", x = 5900000, y = 23)+  
#   annotate("text", label = "2018", x = 5900000, y = 36)+  
#   annotate("text", label = "2017", x = 5900000, y = 47)+  
#   annotate("text", label = "2016", x = 5900000, y = 58)+  
#   annotate("text", label = "2015", x = 5900000, y = 64)+  
#   annotate("text", label = "2014", x = 5900000, y = 66)+  
#   annotate("text", label = "2013", x = 5900000, y = 67.25) +
#   theme(plot.background = element_rect(fill = "white")) +
#   theme(
#   panel.background = element_rect(fill = "white"),
#   panel.grid.major = element_line(size = 0.4, linetype = 'solid',
#                                 colour = "grey"), 
#   panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
#                                 colour = "grey"),
#   axis.text.x = element_text(size = 12),
#   axis.title.x = element_text(size = 20),
#   axis.text.y = element_text(size = 11),
#   axis.title.y = element_text(size = 20),
#   plot.title = element_text(size=25)
#   )


#https://stackoverflow.com/a/36227283/6030118
#bp <- dp +
#  geom_point(data = sum_views, colour = 'black', aes(x = seriesViews, y = series))


library(svglite)
ggsave(file="test.png", plot=dp, width = 17, height = 11)

#dp

fig <- ggplotly(dp)
fig
htmlwidgets::saveWidget(fig, "fig.html")
```


```{r series by year}

#4 series posted across two years (byzantine, sengoku, sun yat sen, khosrau)
#replaced series with year in group_by, and add year in transmute
sum_year <- eh %>% 
  group_by(year) %>% 
  transmute(series, views, likes, year, dislikes, comments, duration) %>% 
  summarize(sum(views), vids = length(series), sum(likes), sum(dislikes), sum(comments), sum(duration)) 

names(sum_year) <- c("year","views", "vids", "likes", "dislikes", "comments", "duration")
sum_year


lik <- sum_year %>% transmute(year = year, count = likes, vids = vids)
lik <- cbind(lik, test = rep('like', 9))
dlik <- sum_year %>% transmute(year = year, count = dislikes, vids = vids)
dlik <- cbind(dlik, test = rep('dislike', 9))
tbl <- rbind(lik, dlik)


ggplot(tbl, aes(year, count, fill = test, label = vids)) + 
  geom_col(position = "identity") + ylab("no. of votes") + 
  geom_text(position = "stack", stat = "identity", vjust = -0.5, check_overlap = TRUE)
  
```




```{r gad stuff}
x <- split(eh, eh$series)
summary(eh$views[eh$year > 2017])
b <- eh %>% group_by(series) %>% slice_min(views, n=1)


```


```{r plot year}
#https://stackoverflow.com/a/49719409/6030118 >>> numbers above bars

ggplot(sum_year, aes(x = year, y = views)) + geom_col() + geom_text(aes(label = vids), vjust = -0.5) 
ggplot(sum_year, aes(x = year, y = likes)) + geom_col() + geom_text(aes(label = vids), vjust = -0.5)
ggplot(sum_year, aes(x = year, y = dislikes)) + geom_col() + geom_text(aes(label = vids), vjust = -0.5)
ggplot(sum_year, aes(x = year, y = comments)) + geom_col() + geom_text(aes(label = vids), vjust = -0.5)
ggplot(sum_year, aes(x = year, y = duration)) + geom_col() + geom_text(aes(label = vids), vjust = -0.5)


```





```{r  series stats by topic}

#https://stackoverflow.com/a/26114852/6030118 > no.vid column
ss <- eh %>% 
  group_by(series) %>% 
  transmute(views, likes, dislikes, comments, duration) %>% 
  summarize(sum(views), vids = length(series), sum(likes), sum(dislikes), sum(comments), sum(duration)) 

names(ss) <- c("series","views", "vids", "likes", "dislikes", "comments", "duration")
ss
```











